modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="dimensionlock"
version="1.0.0"
displayName="Dimension Lock"
authors="Ene/Nico"
description='''
A simple server-side mod that allows toggling the Nether and End.
Provides commands to lock, unlock, and manage dimension access.
'''

[[dependencies.dimensionlock]]
modId="neoforge"
type="required"
versionRange="[20,)"
ordering="NONE"
side="BOTH"

[[dependencies.dimensionlock]]
modId="minecraft"
type="required"
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"
